linters:
  PropertySortOrder:
    order: recess
  PlaceholderInExtend:
    enabled: false
  IdSelector:
    enabled: false
  PropertySpelling:
      enabled: true
      extra_properties: ['prince-page-group', 'prince-footnote-policy', 'prince-image-resolution']
