linters:
  PropertySortOrder:
    order: recess
  PlaceholderInExtend:
    enabled: false
  IdSelector:
    enabled: false
  PropertySpelling:
    enabled: true
    extra_properties: ['prince-page-group', 'prince-footnote-policy', 'prince-image-resolution']
  NestingDepth:
    enabled: true
    max_depth: 4
